#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class CheckBox;
                ref class TextBox;
                ref class Button;
            }
        }
    }
}

namespace ChecksumVerifier
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::StackPanel^ contentPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ checksumsPanel;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ sha512Checkbox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ sha512Text;
        private: ::Windows::UI::Xaml::Controls::Button^ sha512CopyButton;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ sha256Checkbox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ sha256Text;
        private: ::Windows::UI::Xaml::Controls::Button^ sha256CopyButton;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ sha1Checkbox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ sha1Text;
        private: ::Windows::UI::Xaml::Controls::Button^ sha1CopyButton;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ md5Checkbox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ md5Text;
        private: ::Windows::UI::Xaml::Controls::Button^ md5CopyButton;
        private: ::Windows::UI::Xaml::Controls::TextBox^ filePathText;
        private: ::Windows::UI::Xaml::Controls::Button^ fileBrowseButton;
    };
}

